[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xbap"
version = "0.1.0"
description = "X-BAP is a code to do consistent aperture photometry in images that have different PSFs"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}

authors = [
    { name = "Niels de Klerk", email = "nielsklerk03@gmail.com" }
]

dependencies = [
    "numpy",
    "numba",
    "scipy",
    "tqdm",
    "astropy"
]
